services:
  # Бэкенд
  app:
    container_name: express_ts_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Локальный порт:контейнерный порт
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BOT_TOKEN=${BOT_TOKEN} # Токен Telegram бота
    volumes:
      - .:/app
      - /app/node_modules

